package gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.ImagePanel;

public class mainGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainGUI.class.getName());
    
    public mainGUI() {
        initComponents();
        
        jPanel2.setOpaque(false); //tira o fundo do painel dos botoes
        this.setTitle("Mães Que Oram");
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new model.ImagePanel("/static/img/main_background.jpg");
        jPanel2 = new javax.swing.JPanel();
        btn_mae = new javax.swing.JButton();
        btn_encontroC = new javax.swing.JButton();
        btn_encontros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_mae.setBackground(new java.awt.Color(177, 80, 106));
        btn_mae.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_mae.setForeground(new java.awt.Color(255, 255, 255));
        btn_mae.setText("Cadastro de mãe");
        btn_mae.setBorderPainted(false);
        btn_mae.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maeActionPerformed(evt);
            }
        });

        btn_encontroC.setBackground(new java.awt.Color(177, 80, 106));
        btn_encontroC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_encontroC.setForeground(new java.awt.Color(255, 255, 255));
        btn_encontroC.setText("Marcar encontro");
        btn_encontroC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_encontroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encontroCActionPerformed(evt);
            }
        });

        btn_encontros.setBackground(new java.awt.Color(177, 80, 106));
        btn_encontros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_encontros.setForeground(new java.awt.Color(255, 255, 255));
        btn_encontros.setText("Ver encontros");
        btn_encontros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(btn_mae, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(btn_encontroC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(btn_encontros, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mae, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_encontroC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_encontros, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 237, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_maeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maeActionPerformed
        MaeGUI telaMae = new MaeGUI();
        telaMae.setLocationRelativeTo(this);
        telaMae.setVisible(true);
    }//GEN-LAST:event_btn_maeActionPerformed

    private void btn_encontroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encontroCActionPerformed
        EncontroGUI telaEncontro = new EncontroGUI();
        telaEncontro.setLocationRelativeTo(this);
        telaEncontro.setVisible(true);
    }//GEN-LAST:event_btn_encontroCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        
        java.awt.EventQueue.invokeLater(() -> new mainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_encontroC;
    private javax.swing.JButton btn_encontros;
    private javax.swing.JButton btn_mae;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
